# Write your MySQL query statement below
SELECT E.NAME AS EMPLOYEE, D.NAME AS DEPARTMENT , E.SALARY
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON E.departmentId = D.ID
WHERE (E.DEPARTMENTID, E.SALARY) IN (SELECT DEPARTMENTID, MAX(SALARY) FROM EMPLOYEE GROUP BY DEPARTMENTID)